# Logging configuration
logging:
  config: "file:src/main/resources/logback.xml"

# Camel spring-boot properties
camel:
  springboot:
    # The Camel context name
    name: sample-xml-validation-api
    # Enable stream caching
    stream-caching-enabled: true
    # Enable breadcrumb
    use-breadcrumb: true
    # Enable MDC logging
    #deprecated: use-m-d-c-logging: true
    use-mdc-logging: true 
  component:
    # Autoconfiguration for the Camel servlet component
    servlet:
      mapping:
        contextPath: /*

# Binding health checks to an internal port
management:
  server:
    port: 8081
    
  # Disable all management enpoints except info, health, metrics and spring-cloud restart endpoints
  enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    restart:
      enabled: true

  # Expose info, health and metrics endpoints
  endpoints:
    web:
      exposure:
        include: info,health,metrics

# Server listening port
server:
  port: 8080