# Binding health checks to an internal port
management:
  server:
    port: 8081
    
  # Disable all management enpoints except info, jolokia, hawtio, health, metrics and spring-cloud restart endpoints
  enabled-by-default: false
  endpoint:
    info:
      enabled: true
    jolokia:
      enabled: true
      sensitive: false
    hawtio:
      enabled: true
      sensitive: false
    health:
      enabled: true
    metrics:
      enabled: true
    restart:
      enabled: true

  # Expose info, health and metrics endpoints
  endpoints:
    web:
      exposure:
        include: info,health,metrics

# Disable embedded HawtIO authentication
hawtio:
  authenticationEnabled: false

logging:
  config: "file:src/main/resources/logback.xml"

# The name of the Camel app
camel:
  springboot:
    name: "camel-amq"
    # Keeps the application alive
    main-run-controller: true

# AMQP connection configuration
amqp:
  # host, port, max-connections and max-active-sessions-per-connection can be overriden 
  # via the camel-amq configmap object 
  host: amq-ssl-broker-amqp-1-svc-rte-amq7-broker-cluster.apps.cluster-eb10.sandbox1401.opentlc.com
  port: 443
  max-connections: 1
  max-active-sessions-per-connection: 500
  # username and password can be overriden via the camel-amq secret object 
  username: "amq-user"
  password: "P@ssw0rd"
    
# Timer period configuration (can be overriden via the camel-amq configmap object)
timer:
  period-in-ms: 5000

# Welcome message (can be overriden via the camel-amq configmap object)
hello:
  message: "Welcome to Red Hat Fuse on OpenShift Labs"
