spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: "camel-amq-sa"
      volumes:
        - name: "camel-amq"
          secret:
            # The secret must be created before deploying this application
            secretName: "camel-amq"
      containers:
        - name: "camel-amq-kubernetes-config"
          volumeMounts:
            - name: "camel-amq"
              readOnly: true
              # Mount the secret where spring-cloud-kubernetes is configured to read it
              # see src/main/resources/bootstrap.yml
              mountPath: "/etc/secrets/camel-amq"
          resources:
            requests:
              cpu: "0.03"
              memory: "512Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":1, "worker-threads":5 }}}'
            - name: AB_JOLOKIA_AUTH_OPENSHIFT
              value: false
            - name: AB_JOLOKIA_PASSWORD_RANDOM
              value: false
            - name: AB_JOLOKIA_HTTPS
              value: true
          imagePullPolicy: Always
          volumeMounts:
            - name: "camel-amq"
              mountPath: "/deployments/config"
      volumes:
        - name: "camel-amq"
          configMap:
            name: "camel-amq"
