apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "camel-amq-sa"
roleRef:
  # Add the view role to the service account
  kind: "Role"
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "camel-amq-sa"
