spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: "sample-json-validation-api-sa"
      containers:
        - name: "sample-json-validation-api"
          resources:
            requests:
              cpu: "0.2"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "256Mi"
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":1, "worker-threads":10 }}}'
            - name: AB_JOLOKIA_AUTH_OPENSHIFT
              value: false
            - name: AB_JOLOKIA_PASSWORD_RANDOM
              value: false
            - name: AB_JOLOKIA_HTTPS
              value: true
          imagePullPolicy: Always
          volumeMounts:
            - name: "sample-json-validation-api"
              mountPath: "/deployments/config"
      volumes:
        - name: "sample-json-validation-api"
          configMap:
            name: "sample-json-validation-api"
  triggers:
  - type: ConfigChange
  - imageChangeParams:
     automatic: true
     containerNames:
     - sample-json-validation-api
     from:
       kind: ImageStreamTag
       name: sample-json-validation-api:latest