apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "sample-json-validation-api"
roleRef:
  # Add the view Cluster Role to the service account
  kind: "ClusterRole"
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "sample-json-validation-api-sa"
